#!/bin/bash



echo "Enter any command:"
read program

case "${program}" in
	clean)
		echo "Clean is invoked"
		;;
	build)
		echo "Build is invoked"
		;;
	*)
		echo "${program}" is not supported by this application
		exit 2
		;;
esac
